# GENERATE DATA

OLD ERRORAS WHEN USING JOBLIB(works single type on python 3.7.12 and multi one is throwing thrashing kinda error

with base 3.12.4 no multi error but inhomogenous librosa error idk y
)


WORKING ON PYTHON 3.7.12




In [ ]:
from Melokai.brewData import *

brew()

# Process data for MODEL 1

In [32]:
from Melokai.dataReadFromDisk import *
df = load_df_from_csv()
df = df[df["total_length"]<120]
df=df[:500]

DataFrame loaded from: E:\Notebooks\osu\processed-metadata\processed-metadata.csv


In [33]:
df

audio  split  \
0     00edd6f9da5510c28586f651019657d7  train   
1     00ad908443273dc7393a95477945b868  train   
2     00350fbcf85892d611554dd5dadc03f7  train   
5     00b913aa51b331fb279853125858c4f3  train   
6     008b739aabdf6a7726dcbc1edde1e319  train   
...                                ...    ...   
1152  1c3846ce914bd2ba4f575f82c9e1d370  train   
1154  1c75c248c1d3dd9ce3633bf46bac63fa  train   
1155  1c731194e63d0e1017282ad74c678234  train   
1156  1c6dbf271cd70f83ac3ee30e693e7344  train   
1157  1c671f9413ce3064b59cb65470f57e71  train   

                                folder  beatmapset_id  beatmap_id  approved  \
0     55d4aa11a87fd7c535b4976bfe71bbdf         998531     2088521         1   
1     dc9b6cdc6499a5416908365751af36c4         347170      766202         1   
2     6b353feb524ad0ea221b6f566bfef6ad          52222      161653         1   
5     d71702b690bba4766627fb620ddd5275         925343     1932923         1   
6     eb3e2260d1597f1f4214f382ee83a3d1         288974      653568         1   
...                                ...            ...         ...       ...   
1152  469d64da27b0daab50183d9387304c2e         645142     1368008         1   
1154  2c02c30354057a9c003edd717b192b2c         597840     1263789         1   
1155  34e39a759b839a0b6727d139c4eae3ec         974356     2106255         1   
1156  60e7534da2ec4c74f2263b19144fa044         440706      960985         1   
1157  430c4bb6cc44ae1bfed271e00f9a1bf1         716976     1515651         1   

      total_length  hit_length         version  \
0               89          88           Extra   
1              113         102          Expert   
2              101          89          Master   
5              116         116           Extra   
6               74          70   deetz' Insane   
...            ...         ...             ...   
1152            36          36   Yugu's Insane   
1154            46          44          Expert   
1155            80          79  Left's Another   
1156            87          87  Enjoy's Insane   
1157            88          88   Habi's Insane   

                              file_md5  ...  difficultyrating  StackLeniency  \
0     00edd6f9da5510c28586f651019657d7  ...           5.32152            0.2   
1     00ad908443273dc7393a95477945b868  ...           5.44271            0.7   
2     00350fbcf85892d611554dd5dadc03f7  ...           4.90364            0.7   
5     00b913aa51b331fb279853125858c4f3  ...           5.90941            0.7   
6     008b739aabdf6a7726dcbc1edde1e319  ...           5.12834            0.7   
...                                ...  ...               ...            ...   
1152  1c3846ce914bd2ba4f575f82c9e1d370  ...           4.85610            0.5   
1154  1c75c248c1d3dd9ce3633bf46bac63fa  ...           5.20480            0.7   
1155  1c731194e63d0e1017282ad74c678234  ...           5.19672            0.2   
1156  1c6dbf271cd70f83ac3ee30e693e7344  ...           4.94580            0.7   
1157  1c671f9413ce3064b59cb65470f57e71  ...           4.84626            0.7   

      DistanceSpacing  BeatDivisor  HPDrainRate  CircleSize  \
0                 1.0          4.0          6.5         4.0   
1                 0.5          4.0          7.0         5.0   
2                 1.0          4.0          7.0         4.0   
5                 0.9          4.0          5.2         3.8   
6                 1.2          4.0          6.0         4.0   
...               ...          ...          ...         ...   
1152              0.2          8.0          6.0         3.8   
1154              1.5          4.0          6.2         4.0   
1155              2.7          8.0          5.7         4.0   
1156              3.0          4.0          7.0         4.0   
1157              2.1          4.0          7.0         4.0   

      OverallDifficulty  ApproachRate SliderTickRate SliderMultiplier  
0                   8.5           9.3            1.0             1.76  
1                   8.5         

In [35]:
num_of_batch,input_audios,output_beatmaps,processed_beatmap_list,hyper_params_list = new_process_audio_and_beatmap_for_model_all_and_save(df)

Nan or not float found in params in single func
Nan or not float found in params
Nan or not float found in params in single func
Nan or not float found in params
Nan or not float found in params in single func
Nan or not float found in params
Nan or not float found in params in single func
Nan or not float found in params
Nan or not float found in params in single func
Nan or not float found in params


In [36]:
print(len(input_audios))
print(len(input_audios[40]))
print(len(output_beatmaps[40]))
print(len(processed_beatmap_list[40]))
print(len(hyper_params_list[40]))

495
794
794
794
11


In [37]:
for h in processed_beatmap_list[0]:
    print(h)

[755   5   0]
[837   0   0]
[920   1   0]
[1003    0    0]
[1086    0    0]
[1169    0    0]
[1252    5    0]
[1335    0    0]
[1417    1    0]
[1500    0    0]
[1583    0    0]
[1666    0    0]
[1749    5    0]
[1832    0    0]
[1915    1    0]
[1998    0    0]
[2080    0    0]
[2163    0    0]
[2246    5    0]
[2329    0    0]
[2412    1    0]
[2495    0    0]
[2578    0    0]
[2661    0    0]
[2743    5    0]
[2826    0    0]
[2909    1    0]
[2992    0    0]
[3075    1    0]
[3158    0    0]
[3241    1    0]
[3324    0    0]
[3406    5    0]
[3489    0    0]
[3572    1    0]
[3655    0    0]
[3738    0    0]
[3821    0    0]
[3904    5    0]
[3987    0    0]
[4069    0    0]
[4152    1    0]
[4235    0    0]
[4318    0    0]
[4401    5    0]
[4484    0    0]
[4567    1    0]
[4650    0    0]
[4732    0    0]
[4815    0    0]
[4898    5    0]
[4981    0    0]
[5064    1    0]
[5147    0    0]
[5230    0    0]
[5313    0    0]
[5395    5    0]
[5478    0    0]
[5561    1    0]
[5644 

In [39]:
# Mapping of (first_column, second_column) pair to specific index in 21-feature space
combination_map = {
    (0, 0): 0,

    (1, 0): 1, 
    (5, 0): 1, 

    (2, 0): 2, (2, 1): 3, (2, 2): 4,
    (6, 0): 2, (6, 1): 3, (6, 2): 4,

    (8, 0): 5, (8, 1): 6, (8,2):7,
    (12, 0): 5, (12, 1): 6, (12,2):7,

}

# Output list of 21-features
output_8_features = []

for op in output_beatmaps:
    temp = []
    
    # For each row in the op, create a 21-element array with zeros
    for row in op:
        feature_row = np.zeros(8, dtype=int)
        
        # Get the values of the first and second columns
        first_col, second_col = row[0], row[1]
        
        # Check if this (first_col, second_col) pair exists in the combination_map
        if (first_col, second_col) in combination_map:
            # Set the corresponding position to 1
            index = combination_map[(first_col, second_col)]
            feature_row[index] = 1
        
        # Append the feature row to temp
        temp.append(feature_row)
    
    # Convert temp to a numpy array and append to output_21_features
    output_8_features.append(np.array(temp))







In [40]:
input_audios_with_hyperparams = []

for index, ia in enumerate(input_audios):
    temp = []
    for row in ia:
        new_row = np.concatenate((row, hyper_params_list[index]))
        temp.append(new_row)

    input_audios_with_hyperparams.append(temp)

In [41]:
for o in input_audios_with_hyperparams[1]:
    print(o)

[-64.5300216675  40.9836807251   4.0828156471   8.4232873917
   4.1186494827   6.6133060455   3.2416040897   4.9046010971
   1.4594857693   2.4610815048  -0.2458654642   0.7672982216
   3.453564167  186.           113.             0.7
   0.5            4.             7.             5.
   8.5            9.             1.             1.74        ]
[ 21.6403846741  19.5021953583   0.2575111389   9.5809249878
   5.9875421524   9.7713050842  14.0549278259  13.275018692
   5.8333687782   4.7297792435   0.1315180063   2.578854084
   2.7934603691 186.           113.             0.7
   0.5            4.             7.             5.
   8.5            9.             1.             1.74        ]
[ 10.9933872223  27.0124549866   2.351495266    5.6791749001
   6.7468719482   6.7792444229   9.1253547668   8.4873552322
   7.7239046097   6.7673816681   8.1683492661   5.1365323067
   1.6973344088 186.           113.             0.7
   0.5            4.             7.             5.
   8.5            9.

# MODEL TO TRAIN
on python 3.12.4


In [42]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
print(tf.__version__)
print(keras.__version__)

2.17.0
3.5.0


In [43]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)

In [44]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Example variables
input_list = input_audios_with_hyperparams  # This is your list of song inputs, where each song is (num_beats, 13)
output_list = output_8_features  # This is your list of song outputs, where each song is (num_beats, 2)

# Parameters
num_input_features = 13  # 13 features per beat in input
num_output_features = 8  # 2 features to predict per beat

# Padding sequences (songs) to handle variable length songs
padded_inputs = pad_sequences(input_list, padding='post', dtype='float32')
padded_outputs = pad_sequences(output_list, padding='post', dtype='float32')

In [46]:
for p in padded_outputs[5]:
    print(p)

[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0.

new

In [49]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, LSTM, Dense, Masking, TimeDistributed # type: ignore
from tensorflow.keras.models import Model # type: ignore

# Example variables (replace with your actual data)
num_input_features = 24  # Updated to 24 features per beat (including hyperparameters)
num_output_features = 8  # Number of output categories per beat

# Model Definition using Keras Functional API
# Song input (sequence input)
song_input = Input(shape=(None, num_input_features), name="song_input")

# Add Masking layer to ignore padding
masked_input = Masking(mask_value=0)(song_input)

# LSTM layer for sequence data
lstm_output = LSTM(units=64, return_sequences=True)(masked_input)

# TimeDistributed layer with Dense output, softmax activation for classification
output = TimeDistributed(Dense(units=num_output_features, activation='softmax'))(lstm_output)
# Define the model with one input
model = Model(inputs=song_input, outputs=output)

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Summary of the model
model.summary()

# Assuming padded_inputs and padded_outputs are prepared as specified
# Train the model
# padded_inputs: (num_samples, time_steps, 24)
# padded_outputs: (num_samples, time_steps, 8)



Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ song_input          │ (None, None, 24)  │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal_3         │ (None, None, 24)  │          0 │ song_input[0][0]  │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ masking_2 (Masking) │ (None, None, 24)  │          0 │ song_input[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ any_4 (Any)         │ (None, None)      │          0 │ not_equal_3[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_2 (LSTM)       │ (None, None, 64)  │     22,784 │ masking_2[0][0],  │
│                     │                   │            │ any_4[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed_2  │ (None, None, 8)   │        520 │ lstm_2[0][0],     │
│ (TimeDistributed)   │                   │            │ any_4[0][0]       │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 23,304 (91.03 KB)

 Trainable params: 23,304 (91.03 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
# Example for training (replace padded_inputs and padded_outputs with actual data)
model.fit(padded_inputs, padded_outputs, epochs=5, batch_size=30, validation_split=0.2)

Epoch 1/5
14/14 ━━━━━━━━━━━━━━━━━━━━ 1439s 104s/step - accuracy: 0.1017 - loss: 2.0189 - val_accuracy: 0.6160 - val_loss: 1.6979
Epoch 2/5
14/14 ━━━━━━━━━━━━━━━━━━━━ 1118s 80s/step - accuracy: 0.6403 - loss: 1.6812 - val_accuracy: 0.6774 - val_loss: 1.5756
Epoch 3/5
14/14 ━━━━━━━━━━━━━━━━━━━━ 1117s 81s/step - accuracy: 0.6731 - loss: 1.5806 - val_accuracy: 0.6782 - val_loss: 1.5430
Epoch 4/5
14/14 ━━━━━━━━━━━━━━━━━━━━ 1181s 84s/step - accuracy: 0.6743 - loss: 1.5525 - val_accuracy: 0.6843 - val_loss: 1.5304
Epoch 5/5
14/14 ━━━━━━━━━━━━━━━━━━━━ 1135s 82s/step - accuracy: 0.6770 - loss: 1.5352 - val_accuracy: 0.6831 - val_loss: 1.5232


In [52]:
# Save the model to a file
tf.keras.models.save_model(model, 'new1.keras')

In [53]:
# Load the model from the file
loaded_model = tf.keras.models.load_model('new1.keras')


In [56]:
# Assuming the model is trained and padded_inputs[0] is your test input
# padded_inputs[0]: shape (time_steps, num_input_features)
test_input = np.expand_dims(padded_inputs[43], axis=0)  # Add batch dimension, shape becomes (1, time_steps, 24)

# Get the model prediction
predicted_output = model.predict(test_input)

# predicted_output will be of shape (1, time_steps, num_output_features), we remove the batch dimension to print it
predicted_output = np.squeeze(predicted_output, axis=0)  # Shape: (time_steps, num_output_features)



1/1 ━━━━━━━━━━━━━━━━━━━━ 21s 21s/step


In [57]:
predicted_classes = np.argmax(predicted_output, axis=-1)

# Convert to one-hot encoding (hardmax transformation)
one_hot_predictions = np.zeros_like(predicted_output)

# Set the max probability class index to 1, others remain 0
for i, class_idx in enumerate(predicted_classes):
    one_hot_predictions[i, class_idx] = 1


for p in one_hot_predictions:
    print(p)

[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0.

above model

In [ ]:
import numpy as np
from tensorflow.keras.layers import Input, LSTM, Dense, Masking, Concatenate, RepeatVector, TimeDistributed
from tensorflow.keras.models import Model


# Example variables (you can replace these with your actual data)
input_list = input_audios  # List of song inputs, each song is (num_beats, 13)
output_list = output_21_features  # List of song outputs, each song is (num_beats, 21)
hyperparameters = hyper_params_list  # List of hyperparameters, one for each song (495, 11)

# Parameters
num_input_features = 13      # Number of features per beat in input
num_output_features = 21     # Number of output categories per beat
num_hyperparameters = 11      # Number of hyperparameters per song

# Convert hyperparameters list to numpy array
hyperparameters = np.array(hyperparameters)

# Padding sequences to handle variable length songs
padded_inputs = pad_sequences(input_list, padding='post', dtype='float32')
padded_outputs = pad_sequences(output_list, padding='post', dtype='float32')

# Model Definition
# Song input (sequence input)
song_input = Input(shape=(None, num_input_features), name="song_input")

# Add Masking layer to ignore padding
masked_input = Masking(mask_value=0)(song_input)

# LSTM layer for sequence data
lstm_output = LSTM(units=64, return_sequences=True)(masked_input)

# Hyperparameters input (static input for each song)
hyperparameters_input = Input(shape=(num_hyperparameters,), name="hyperparameters_input")

# Repeat the hyperparameters for each time step of the sequence
# Use the shape of lstm_output to determine how many repetitions are needed
# Correctly repeat hyperparameters for the sequence length
hyperparameters_repeated = RepeatVector(tf.shape(lstm_output)[1])(hyperparameters_input)

# Concatenate LSTM output with repeated hyperparameters
concatenated = Concatenate(axis=-1)([lstm_output, hyperparameters_repeated])

# TimeDistributed layer with Dense output, softmax activation for classification
output = TimeDistributed(Dense(units=num_output_features, activation='softmax'))(concatenated)

# Define the model with two inputs
model = Model(inputs=[song_input, hyperparameters_input], outputs=output)

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Summary of the model
model.summary()

# Prepare the hyperparameters to match the input shape for training
# Ensure hyperparameters are repeated based on the batch size only
# Using padded_inputs.shape[0] which corresponds to the number of songs
hyperparameters_repeated_for_batch = np.repeat(hyperparameters, padded_inputs.shape[1], axis=0).reshape(padded_inputs.shape[0], -1)

# Train the model with padded inputs and corresponding hyperparameters
# model.fit([padded_inputs, hyperparameters], padded_outputs, epochs=10, batch_size=16, validation_split=0.2)


In [ ]:
model.fit([padded_inputs, hyperparameters], padded_outputs, epochs=10, batch_size=16, validation_split=0.2)

In [ ]:
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, LSTM, Dense, Masking, TimeDistributed, Concatenate, Layer
from tensorflow.keras.models import Model

# Example variables (replace with your actual data)
num_input_features = 13      # Number of features per beat in input
num_output_features = 21     # Number of output categories per beat
num_hyperparameters = 11      # Number of hyperparameters per song

# Custom layer to repeat hyperparameters
class RepeatHyperparameters(Layer):
    def call(self, inputs):
        hyperparameters_input = inputs[0]
        lstm_output = inputs[1]
        # Repeat hyperparameters for each time step of the sequence
        repeated_hyperparameters = tf.repeat(hyperparameters_input[:, tf.newaxis, :], tf.shape(lstm_output)[1], axis=1)
        return tf.concat([lstm_output, repeated_hyperparameters], axis=-1)

# Model Definition using Keras Functional API
# Song input (sequence input)
song_input = Input(shape=(None, num_input_features), name="song_input")

# Add Masking layer to ignore padding
masked_input = Masking(mask_value=0)(song_input)

# LSTM layer for sequence data
lstm_output = LSTM(units=64, return_sequences=True)(masked_input)

# Hyperparameters input (static input for each song)
hyperparameters_input = Input(shape=(num_hyperparameters,), name="hyperparameters_input")

# Use the custom layer to concatenate LSTM output with repeated hyperparameters
combined_output = RepeatHyperparameters()([hyperparameters_input, lstm_output])

# TimeDistributed layer with Dense output, softmax activation for classification
output = TimeDistributed(Dense(units=num_output_features, activation='softmax'))(combined_output)

# Define the model with two inputs
model = Model(inputs=[song_input, hyperparameters_input], outputs=output)

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Summary of the model
model.summary()

# Train the model
# Prepare hyperparameters for each song (ensure it's a NumPy array of shape (num_samples, num_hyperparameters))
hyperparameters = np.array(hyper_params_list)  # Should have shape (num_samples, 11)

# Train the model with padded inputs and corresponding hyperparameters
model.fit([padded_inputs, hyperparameters], padded_outputs, epochs=10, batch_size=16, validation_split=0.2)


In [ ]:
model.save("my_model.h5")

In [17]:
# Save the model using the native Keras format
model.save('my_model.keras')


In [ ]:
from tensorflow import keras
keras.saving.save_model(model, 'my_model.keras')

In [ ]:
from tensorflow.keras.models import load_model

# Custom layer to repeat hyperparameters
class RepeatHyperparameters(Layer):
    def call(self, inputs):
        hyperparameters_input = inputs[0]
        lstm_output = inputs[1]
        # Repeat hyperparameters for each time step of the sequence
        repeated_hyperparameters = tf.repeat(hyperparameters_input[:, tf.newaxis, :], tf.shape(lstm_output)[1], axis=1)
        return tf.concat([lstm_output, repeated_hyperparameters], axis=-1)


# Ensure the custom layer RepeatHyperparameters is registered
custom_objects = {'RepeatHyperparameters': RepeatHyperparameters}

# Load the model with custom objects
model = load_model('my_model.h5', custom_objects=custom_objects)


In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Masking, TimeDistributed
from tensorflow.keras.utils import to_categorical

# Model Definition
model = Sequential()

# Add Masking layer to ignore padding (e.g., padded zeros)
model.add(Masking(mask_value=0, input_shape=(None, num_input_features)))

# LSTM layer with 64 units, returns sequences to match time-distributed output
model.add(LSTM(units=64, return_sequences=True))

# TimeDistributed layer with Dense output, softmax activation for classification
model.add(TimeDistributed(Dense(units=num_output_features, activation='softmax')))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Summary of the model
model.summary()

# Train the model
model.fit(padded_inputs, padded_outputs, epochs=10, batch_size=16, validation_split=0.2)

In [ ]:
# Print the padded inputs/outputs to visualize
print("Padded Inputs Shape:", padded_inputs.shape)
# print("Padded Inputs Data:\n", padded_inputs)
# print("\nPadded Outputs Shape:", padded_outputs.shape)
# print("Padded Outputs Data:\n", padded_outputs)
for i in padded_outputs[1]:
    print(i)