# GENERATE DATA

In [1]:
from Melokai.brewData import *

brew()

e:\Notebooks\osu\Melokai\preprocessaudio.py:148: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  features = np.array(features)
c:\Users\darsh\anaconda3\envs\gpuEnv\lib\site-packages\librosa\core\spectrum.py:267: UserWarning: n_fft=2048 is too large for input signal of length=1736
  f"n_fft={n_fft} is too large for input signal of length={y.shape[-1]}"


Processed 1 files
Processed 2 files
DataFrame saved as a CSV at: processed-metadata\processed-metadata.csv
Total errors encountered: 0


# Process data for MODEL 1

In [1]:
from Melokai.dataReadFromDisk import *
df = load_df_from_csv()

DataFrame loaded from: E:\Notebooks\osu\processed-metadata\processed-metadata.csv


In [2]:
num_of_batch,processed_audio_list,processed_beatmap_list,hyper_params_list = new_process_audio_and_beatmap_for_model_all_and_save(df)

diff for a[0]=837 and hitobj[2] 3194.0 is 2357
this1 for 837
diff for a[0]=944 and hitobj[2] 3194.0 is 2250
this1 for 944
diff for a[0]=1051 and hitobj[2] 3194.0 is 2143
this1 for 1051
diff for a[0]=1158 and hitobj[2] 3194.0 is 2036
this1 for 1158
diff for a[0]=1265 and hitobj[2] 3194.0 is 1929
this1 for 1265
diff for a[0]=1372 and hitobj[2] 3194.0 is 1822
this1 for 1372
diff for a[0]=1479 and hitobj[2] 3194.0 is 1715
this1 for 1479
diff for a[0]=1587 and hitobj[2] 3194.0 is 1607
this1 for 1587
diff for a[0]=1694 and hitobj[2] 3194.0 is 1500
this1 for 1694
diff for a[0]=1801 and hitobj[2] 3194.0 is 1393
this1 for 1801
diff for a[0]=1908 and hitobj[2] 3194.0 is 1286
this1 for 1908
diff for a[0]=2015 and hitobj[2] 3194.0 is 1179
this1 for 2015
diff for a[0]=2122 and hitobj[2] 3194.0 is 1072
this1 for 2122
diff for a[0]=2229 and hitobj[2] 3194.0 is 965
this1 for 2229
diff for a[0]=2337 and hitobj[2] 3194.0 is 857
this1 for 2337
diff for a[0]=2444 and hitobj[2] 3194.0 is 750
this1 for 2444

In [8]:
print(len(processed_audio_list[1]))
print(len(processed_beatmap_list[1]))

1726
1726


In [5]:
for h in processed_beatmap_list[0]:
    print(h)

[837   0   0]
[944   0   0]
[1051    0    0]
[1158    0    0]
[1265    0    0]
[1372    0    0]
[1479    0    0]
[1587    0    0]
[1694    0    0]
[1801    0    0]
[1908    0    0]
[2015    0    0]
[2122    0    0]
[2229    0    0]
[2337    0    0]
[2444    0    0]
[2551    0    0]
[2658    0    0]
[2765    0    0]
[2872    0    0]
[2979    0    0]
[3087    0    0]
[3194    5    0]
[3301    0    0]
[3408    5    0]
[3515    0    0]
[3622    1    0]
[3729    0    0]
[3837    5    0]
[3944    0    0]
[4051    1    0]
[4158    0    0]
[4265    5    0]
[4372    0    0]
[4479    0    0]
[4587    0    0]
[4694    0    0]
[4801    0    0]
[4908    0    0]
[5015    0    0]
[5122    1    0]
[5229    0    0]
[5337    0    0]
[5444    0    0]
[5551    0    0]
[5658    0    0]
[5765    0    0]
[5872    0    0]
[5979    5    0]
[6087    1    0]
[6194    0    0]
[6301    0    0]
[6408    0    0]
[6515    0    0]
[6622    0    0]
[6729    0    0]
[6837    0    0]
[6944    0    0]
[7051    0    0]
[71